# engine:
#   database:
#     type: sqlite
#     uri: ./data/infinite-dungeon.db
#     name: infinite-dungeon

render:
  window:
    width: 1920
    height: 1080
    fullscreen: false
log:
  level: DEBUG
