# engine:
#   database:
#     type: sqlite
#     uri: ./data/infinite-dungeon.db
#     name: infinite-dungeon

comfyui:
  base_url: http://localhost:8000
  workflow_folder: /Users/sebas/Projects/infinite-dungeon/app/assets/workflows

render:
  window:
    width: 960
    height: 540
    fullscreen: false
log:
  level: DEBUG
